# Checkpoint Two: Exploratory Data Analysis

Now that your chosen dataset is approved, it is time to start working on your analysis. Use this notebook to perform your EDA and make notes where directed to as you work.

## Getting Started

Since we have not provided your dataset for you, you will need to load the necessary files in this repository. Make sure to include a link back to the original dataset here as well.

My dataset:

Your first task in EDA is to import necessary libraries and create a dataframe(s). Make note in the form of code comments of what your thought process is as you work on this setup task.

In [122]:
import pandas as pd
import numpy as np
import seaborn as sns #visualisation
import matplotlib.pyplot as plt #visualisation


data = pd.read_csv("perfume.csv")
df = pd.DataFrame(data)

df

#I import pandas and numpy in order to important data and handle analysis. 
#I import seaborn and matplotlib for visualizations.
#It looks like this datast was taken off of Kaggle. I have the spreadsheet but I cannot add the link.

,brand,title,date,accords,rating_score,votes,longevity_poor,longevity_weak,longevity_moderate,longevity_long,...,notes_12,notes_13,notes_14,notes_15,notes_16,notes_17,notes_18,notes_19,notes_20,gender
0,The-Spirit-of-Dubai,Aamal The Spirit of Dubai for women and men,2017,"woody,earthy,animalic,amber,musky,balsamic",5.00,3,0,0,0,0,...,Base3Moss,Base4Agarwood (Oud),Base5Indian Oud,NaN,NaN,NaN,NaN,NaN,NaN,women
1,Ajmal,Aatifa Ajmal for women and men,2014,"fresh spicy,woody,musky,rose,amber",4.20,10,1,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
2,Al-Jazeera-Perfumes,AA Al-Jazeera Perfumes for women and men,0,"rose,woody,musky,oud,fruity",0.00,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
3,Art-of-Scent-Swiss-Perfumes,aarewasser Art of Scent - Swiss Perfumes for w...,2010,"white floral,green,ozonic,fresh,animalic",0.00,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
4,Hamidi-Oud-Perfumes,Aaliyah Hamidi Oud & Perfumes for women and men,0,"woody,warm spicy,amber,balsamic,musky",0.00,2,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51207,Maitre-Parfumeur-et-Gantier,Oud Extravagant Maitre Parfumeur et Gantier fo...,2018,"balsamic,oud,aromatic,fresh spicy,vanilla,smok...",3.67,5,1,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
51208,Como-Lake,Silenzio Como Lake for women and men,2018,"woody,musky,aromatic,amber,white floral,citrus...",0.00,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
51209,Battistoni,Marte Red Planet Battistoni for men,0,"aromatic,green,citrus,woody,fresh spicy,amber,...",0.00,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51210,12-Parfumeurs-Francais,Versailles 12 Parfumeurs Francais for women an...,2015,"warm spicy,woody,citrus,fruity,sweet",0.00,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
51211,OPSObjects,Ops! Love OPSObjects for women,2015,"floral,citrus,fresh,aromatic,patchouli,musky,P...",0.00,1,1,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women

## Get to Know the Numbers

Now that you have everything setup, put any code that you use to get to know the dataframe and its rows and columns better in the cell below. You can use whatever techniques you like, except for visualizations. You will put those in a separate section.

When working on your code, make sure to leave comments so that your mentors can understand your thought process.

In [4]:
df.head()

#Looks like it's organized by the title of the fragrance. There are a lot of NaN

,brand,title,date,accords,rating_score,votes,longevity_poor,longevity_weak,longevity_moderate,longevity_long,...,notes_12,notes_13,notes_14,notes_15,notes_16,notes_17,notes_18,notes_19,notes_20,gender
0,The-Spirit-of-Dubai,Aamal The Spirit of Dubai for women and men,2017,"woody,earthy,animalic,amber,musky,balsamic",5.0,3,0,0,0,0,...,Base3Moss,Base4Agarwood (Oud),Base5Indian Oud,NaN,NaN,NaN,NaN,NaN,NaN,women
1,Ajmal,Aatifa Ajmal for women and men,2014,"fresh spicy,woody,musky,rose,amber",4.2,10,1,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
2,Al-Jazeera-Perfumes,AA Al-Jazeera Perfumes for women and men,0,"rose,woody,musky,oud,fruity",0.0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
3,Art-of-Scent-Swiss-Perfumes,aarewasser Art of Scent - Swiss Perfumes for w...,2010,"white floral,green,ozonic,fresh,animalic",0.0,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
4,Hamidi-Oud-Perfumes,Aaliyah Hamidi Oud & Perfumes for women and men,0,"woody,warm spicy,amber,balsamic,musky",0.0,2,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women

In [5]:
df.tail()

,brand,title,date,accords,rating_score,votes,longevity_poor,longevity_weak,longevity_moderate,longevity_long,...,notes_12,notes_13,notes_14,notes_15,notes_16,notes_17,notes_18,notes_19,notes_20,gender
51207,Maitre-Parfumeur-et-Gantier,Oud Extravagant Maitre Parfumeur et Gantier fo...,2018,"balsamic,oud,aromatic,fresh spicy,vanilla,smok...",3.67,5,1,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
51208,Como-Lake,Silenzio Como Lake for women and men,2018,"woody,musky,aromatic,amber,white floral,citrus...",0.00,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
51209,Battistoni,Marte Red Planet Battistoni for men,0,"aromatic,green,citrus,woody,fresh spicy,amber,...",0.00,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51210,12-Parfumeurs-Francais,Versailles 12 Parfumeurs Francais for women an...,2015,"warm spicy,woody,citrus,fruity,sweet",0.00,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
51211,OPSObjects,Ops! Love OPSObjects for women,2015,"floral,citrus,fresh,aromatic,patchouli,musky,P...",0.00,1,1,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women

In [6]:
df.describe()

,date,rating_score,votes,longevity_poor,longevity_weak,longevity_moderate,longevity_long,longevity_very_long,sillage_soft,sillage_moderate,...,clsday_male25under,clsday_female25older,clsday_male25older,clsnight_female25under,clsnight_male25under,clsnight_female25older,clsnight_male25older,Ihaveit,Ihadit,Iwantit
count,51212.000000,51212.000000,51212.000000,51212.00000,51212.000000,51212.000000,51212.000000,51212.000000,51212.000000,51212.000000,...,51212.000000,51212.000000,51212.000000,51212.000000,51212.000000,51212.000000,51212.00000,51212.000000,51212.000000,51212.000000
mean,1526.492775,3.192377,86.440522,1.88323,2.458252,6.665450,6.477974,3.544931,4.870558,10.671171,...,7.973834,19.904007,19.201261,3.078458,7.334101,10.128564,17.54085,62.045556,0.045497,0.486956
std,867.219020,1.630846,362.674407,6.63654,8.809443,27.960634,34.181818,22.603463,17.328103,43.066644,...,20.805762,24.590240,28.763064,7.941041,20.663062,17.056071,27.95558,267.207478,0.370980,2.006863
min,0.000000,0.000000,0.000000,-1.00000,-2.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,0.000000,0.000000,0.000000
25%,1900.000000,3.000000,2.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,0.000000,0.000000
50%,2009.000000,3.860000,9.000000,0.00000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,6.000000,2.000000,1.000000,1.000000,1.000000,1.00000,5.000000,0.000000,0.000000
75%,2015.000000,4.200000,42.000000,1.00000,2.000000,4.000000,3.000000,2.000000,3.000000,6.000000,...,4.000000,33.000000,28.000000,1.000000,2.000000,13.000000,25.00000,27.250000,0.000000,0.000000
max,9459.000000,5.000000,11188.000000,427.00000,364.000000,1124.000000,1421.000000,1258.000000,906.000000,1815.000000,...,400.000000,200.000000,300.000000,100.000000,400.000000,200.000000,500.00000,8825.000000,44.000000,47.000000

In [9]:
df.shape
#51212 rows, 86 columns - There are a lot of columns here which means there's a lot of potential things to consider for data comparisons.

(51212, 86)

In [11]:
df = df.drop_duplicates()
df

#no duplicates here

,brand,title,date,accords,rating_score,votes,longevity_poor,longevity_weak,longevity_moderate,longevity_long,...,notes_12,notes_13,notes_14,notes_15,notes_16,notes_17,notes_18,notes_19,notes_20,gender
0,The-Spirit-of-Dubai,Aamal The Spirit of Dubai for women and men,2017,"woody,earthy,animalic,amber,musky,balsamic",5.00,3,0,0,0,0,...,Base3Moss,Base4Agarwood (Oud),Base5Indian Oud,NaN,NaN,NaN,NaN,NaN,NaN,women
1,Ajmal,Aatifa Ajmal for women and men,2014,"fresh spicy,woody,musky,rose,amber",4.20,10,1,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
2,Al-Jazeera-Perfumes,AA Al-Jazeera Perfumes for women and men,0,"rose,woody,musky,oud,fruity",0.00,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
3,Art-of-Scent-Swiss-Perfumes,aarewasser Art of Scent - Swiss Perfumes for w...,2010,"white floral,green,ozonic,fresh,animalic",0.00,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
4,Hamidi-Oud-Perfumes,Aaliyah Hamidi Oud & Perfumes for women and men,0,"woody,warm spicy,amber,balsamic,musky",0.00,2,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51207,Maitre-Parfumeur-et-Gantier,Oud Extravagant Maitre Parfumeur et Gantier fo...,2018,"balsamic,oud,aromatic,fresh spicy,vanilla,smok...",3.67,5,1,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
51208,Como-Lake,Silenzio Como Lake for women and men,2018,"woody,musky,aromatic,amber,white floral,citrus...",0.00,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
51209,Battistoni,Marte Red Planet Battistoni for men,0,"aromatic,green,citrus,woody,fresh spicy,amber,...",0.00,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51210,12-Parfumeurs-Francais,Versailles 12 Parfumeurs Francais for women an...,2015,"warm spicy,woody,citrus,fruity,sweet",0.00,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
51211,OPSObjects,Ops! Love OPSObjects for women,2015,"floral,citrus,fresh,aromatic,patchouli,musky,P...",0.00,1,1,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women

In [15]:
print(df.isnull().sum())

brand               0
title               0
date                0
accords           944
rating_score        0
                ...
notes_17        49359
notes_18        49797
notes_19        50149
notes_20        50384
gender          10479
Length: 86, dtype: int64

In [27]:
df.columns
#Trying to see what columns I have because there are so many I can't see them all at once. 
#This will help me figure out which ones I want to look at.

Index(['brand', 'title', 'date', 'accords', 'rating_score', 'votes',
       'longevity_poor', 'longevity_weak', 'longevity_moderate',
       'longevity_long', 'longevity_very_long', 'sillage_soft',
       'sillage_moderate', 'sillage_heavy', 'sillage_enormous', 'clslove',
       'clslike', 'clsdislike', 'clswinter', 'clsspring', 'clssummer',
       'clsautumn', 'clscold', 'clshot', 'clsday', 'clsnight',
       'clslove_female25under', 'clslove_female25older',
       'clslike_female25under', 'clslike_female25older',
       'clsdislike_female25under', 'clsdislike_female25older',
       'clswinter_female25under', 'clswinter_female25older',
       'clsspring_female25under', 'clsspring_female25older',
       'clssummer_female25under', 'clssummer_female25older',
       'clsautumn_female25under', 'clsautumn_female25older',
       'clsday_female25under', 'clsday_female25older',
       'clsnight_female25under', 'clsnight_female25older', 'Ihaveit', 'Ihadit',
       'Iwantit', 'notes_1', 'notes_2', 'notes_3', 'notes_4', 'notes_5',
       'notes_6', 'notes_7', 'notes_8', 'notes_9', 'notes_10', 'notes_11',
       'notes_12', 'notes_13', 'notes_14', 'notes_15', 'notes_16', 'notes_17',
       'notes_18', 'notes_19', 'notes_20', 'gender'],
      dtype='object')

In [29]:
df.drop(['clslove_male25under', 'clslove_male25older', 'clslove_male25under', 'clslike_male25under', 'clslike_male25older', 'clsdislike_male25under', 'clsdislike_male25older','clswinter_male25under', 'clswinter_male25older', 'clsspring_male25under', 'clsspring_male25older', 'clssummer_male25under', 'clssummer_male25older', 'clsautumn_male25under', 'clsautumn_male25older', 'clsday_male25under', 'clsday_male25older', 'clsday_male25under', 'clsnight_male25under', 'clsnight_male25older'], axis=1, inplace=True)
#I'm dropping all of the male related data because our target customers are women.

KeyError: "['clslove_male25under' 'clslove_male25older' 'clslove_male25under'\n 'clslike_male25under' 'clslike_male25older' 'clsdislike_male25under'\n 'clsdislike_male25older' 'clswinter_male25under' 'clswinter_male25older'\n 'clsspring_male25under' 'clsspring_male25older' 'clssummer_male25under'\n 'clssummer_male25older' 'clsautumn_male25under' 'clsautumn_male25older'\n 'clsday_male25under' 'clsday_male25older' 'clsday_male25under'\n 'clsnight_male25under' 'clsnight_male25older'] not found in axis"

In [50]:
df.columns

Index(['brand', 'title', 'date', 'accords', 'rating_score', 'votes',
       'longevity_poor', 'longevity_weak', 'longevity_moderate',
       'longevity_long', 'longevity_very_long', 'sillage_soft',
       'sillage_moderate', 'sillage_heavy', 'sillage_enormous', 'clslove',
       'clslike', 'clsdislike', 'clswinter', 'clsspring', 'clssummer',
       'clsautumn', 'clscold', 'clshot', 'clsday', 'clsnight',
       'clslove_female25under', 'clslove_female25older',
       'clslike_female25under', 'clslike_female25older',
       'clsdislike_female25under', 'clsdislike_female25older',
       'clswinter_female25under', 'clswinter_female25older',
       'clsspring_female25under', 'clsspring_female25older',
       'clssummer_female25under', 'clssummer_female25older',
       'clsautumn_female25under', 'clsautumn_female25older',
       'clsday_female25under', 'clsday_female25older',
       'clsnight_female25under', 'clsnight_female25older', 'Ihaveit', 'Ihadit',
       'Iwantit', 'notes_1', 'notes_2', 'notes_3', 'notes_4', 'notes_5',
       'notes_6', 'notes_7', 'notes_8', 'notes_9', 'notes_10', 'notes_11',
       'notes_12', 'notes_13', 'notes_14', 'notes_15', 'notes_16', 'notes_17',
       'notes_18', 'notes_19', 'notes_20'],
      dtype='object')

In [48]:
df.columns

Index(['brand', 'title', 'date', 'accords', 'rating_score', 'votes',
       'longevity_poor', 'longevity_weak', 'longevity_moderate',
       'longevity_long', 'longevity_very_long', 'sillage_soft',
       'sillage_moderate', 'sillage_heavy', 'sillage_enormous', 'clslove',
       'clslike', 'clsdislike', 'clswinter', 'clsspring', 'clssummer',
       'clsautumn', 'clscold', 'clshot', 'clsday', 'clsnight',
       'clslove_female25under', 'clslove_female25older',
       'clslike_female25under', 'clslike_female25older',
       'clsdislike_female25under', 'clsdislike_female25older',
       'clswinter_female25under', 'clswinter_female25older',
       'clsspring_female25under', 'clsspring_female25older',
       'clssummer_female25under', 'clssummer_female25older',
       'clsautumn_female25under', 'clsautumn_female25older',
       'clsday_female25under', 'clsday_female25older',
       'clsnight_female25under', 'clsnight_female25older', 'Ihaveit', 'Ihadit',
       'Iwantit', 'notes_1', 'notes_2', 'notes_3', 'notes_4', 'notes_5',
       'notes_6', 'notes_7', 'notes_8', 'notes_9', 'notes_10', 'notes_11',
       'notes_12', 'notes_13', 'notes_14', 'notes_15', 'notes_16', 'notes_17',
       'notes_18', 'notes_19', 'notes_20'],
      dtype='object')

In [84]:
df.drop(['notes_1', 'notes_2', 'notes_3', 'notes_4', 'notes_5',
       'notes_6', 'notes_7', 'notes_8', 'notes_9', 'notes_10', 'notes_11',
       'notes_12', 'notes_13', 'notes_14', 'notes_15', 'notes_16', 'notes_17',
       'notes_18', 'notes_19', 'notes_20'], axis=1, inplace=True)

# I decided to drop the notes because there are too many nulls.

In [54]:
df['date'].describe()

count    51212.000000
mean      1526.492775
std        867.219020
min          0.000000
25%       1900.000000
50%       2009.000000
75%       2015.000000
max       9459.000000
Name: date, dtype: float64

In [55]:
df['brand']

0                The-Spirit-of-Dubai
1                              Ajmal
2                Al-Jazeera-Perfumes
3        Art-of-Scent-Swiss-Perfumes
4                Hamidi-Oud-Perfumes
                    ...
51207    Maitre-Parfumeur-et-Gantier
51208                      Como-Lake
51209                     Battistoni
51210         12-Parfumeurs-Francais
51211                     OPSObjects
Name: brand, Length: 51212, dtype: object

In [ ]:
last_ten_years = np.array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020])

In [76]:
df['rating_score']

0        5.00
1        4.20
2        0.00
3        0.00
4        0.00
         ...
51207    3.67
51208    0.00
51209    0.00
51210    0.00
51211    0.00
Name: rating_score, Length: 51212, dtype: float64

In [95]:
df.sort_values(['rating_score', 'accords'], ascending=False).groupby('rating_score').head()

#I am able to see which

,brand,title,date,accords,rating_score,votes,longevity_poor,longevity_weak,longevity_moderate,longevity_long,...,clssummer_female25older,clsautumn_female25under,clsautumn_female25older,clsday_female25under,clsday_female25older,clsnight_female25under,clsnight_female25older,Ihaveit,Ihadit,Iwantit
39684,Frederic-Haldimann,Plaisir de Frederic Frederic Haldimann for women,0,"yellow floral,woody,sweet,white floral,vanilla",5.0,1,0,0,0,1,...,1,1,1,1,1,1,1,0,0,6
19109,Biosea,Parfait Biosea for women,0,"yellow floral,woody,rose,floral,powdery",5.0,2,0,0,0,1,...,1,1,1,1,1,1,1,0,0,4
31347,Dzintars,Lady Dream Comely Dzintars for women,0,"yellow floral,white floral,sweet,citrus,woody,...",5.0,3,0,0,1,0,...,1,50,1,50,1,50,1,1,0,0
3505,Feel-Oud,Oud Champi Feel Oud for women and men,2019,"yellow floral,sweet,floral",5.0,1,0,0,0,0,...,1,1,1,1,1,1,1,1,0,0
23495,CB-I-Hate-Perfume,Jonquil CB I Hate Perfume for women and men,2013,"yellow floral,green,aromatic,floral,herbal",5.0,2,0,0,1,0,...,1,1,1,1,1,1,1,0,0,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10411,Tambela-Natural-Perfumes,Peace,2000,"yellow floral,woody,sweet,vanilla,amber,patchouli",0.0,0,0,0,0,0,...,1,1,1,1,1,1,1,0,0,6
23341,Nobile-1942,Castadiva Estratto Nobile 1942 for women,2009,"yellow floral,woody,green,vanilla,sweet,white ...",0.0,3,0,1,0,0,...,1,1,1,50,1,50,1,0,0,6
35377,Isabelle-T,Elysees No 5 Isabelle T for women,0,"yellow floral,woody,green,earthy,white floral",0.0,1,0,0,0,0,...,1,1,1,1,1,1,1,0,0,1
45504,Irina-Vaganova-,Luxury Code (–ö–æ–¥ –†–æ—Å–∫–æ—à–∏) Irina Vaga...,2016,"yellow floral,white floral,warm spicy,oud,rose...",0.0,0,0,0,0,0,...,1,1,1,1,1,1,1,0,0,0
14755,Grasse-Au-Parfum,No 2 Rayonnante Grasse Au Parfum for women,0,"yellow floral,white floral,sweet,fruity,woody",0.0,0,0,0,0,0,...,1,1,1,1,1,1,1,0,0,0

In [108]:
df['votes'].sum()

4426792

## Visualize

Create any visualizations for your EDA here. Make note in the form of code comments of what your thought process is for your visualizations.

## Summarize Your Results

With your EDA complete, answer the following questions.

1. Was there anything surprising about your dataset? 
2. Do you have any concerns about your dataset? 
3. Is there anything you want to make note of for the next phase of your analysis, which is cleaning data?

In [ ]:
#I was surprised to see so many NaNs in the notes columns. 
#I don't think I need them though since I can use the accords.
#The number of votes per perfume isn't evenly distributed so making comparisons might not be as accurate.